### ISSUE TITLE
Can't compile with ifort

### ISSUE THREAD

**Issue by Poolshark** [zerothi/fdict#12]
Hi!
Sorry for that (maybe) stupid question but I'm trying to compile the library with `ifort` and I have no clue how. I've tried to do `FC=intel` and `FC=ifort` within the `setup.make` but without success. What am I doing wrong?

Thanks!

**Comment by 14NGiestas** [comment]
use
`make FC=ifort`
it should work

**Comment by Poolshark** [comment]
Thanks! That did work! Sorry for bothering you!
