### ISSUE TITLE
Overload the operator(=), to interface the assign and associate functions

### ISSUE THREAD

**Issue by 14NGiestas** [zerothi/fdict#13]
Why not overload the operator(=) instead using subroutines like assign and associate?
[Why did you choose this way? (I'm curious if I can help...)]
```fortran
integer :: numb
type(Var) :: val
numb = 1
val = numb ! Eq: call assign(val, numb)
numb = val ! Eq: call assign(numb, val)
```
[operator overloading](https://en.wikibooks.org/wiki/Fortran/language_extensions#Operator_Overloading)
```fortran
interface operator(=)
    module procedure assign_X_to_Y
    (...)
end interface
```

**Comment by zerothi** [comment]
Ok, you could notify the user via try-catch implementations, but this is beyond the scope of this library.

**Comment by zerothi** [comment]
I have to say that I don't particularly like this. :)

Another problem is how to handle `var = float`. Should it nullify or deallocate the internal data?

Now there can always be standards for taking care of every situation. But I don't particularly like any of the things.
If one wishes to have overloaded operators one can easily generate them and include them.

**Comment by zerothi** [comment]
I am gonna close this issue for now. :)
