### ISSUE TITLE
How to implement in an example

### ISSUE THREAD

**Issue by hkp888** [zerothi/fdict#15]
Hi,
I do not have much experience with coding in Fortran, so I apologize in advance for the basic level question. 

In my case, I have an input file that I read in a subroutine. Each line has this format: 'key1', 'value11', 'value12'. I need to read a new file of this type (being provided by an external program) a few times while the program runs. I would like to store the info from the file in a dictionary to use the key values later in a quick manner. 

A subroutine is called to read the new file whenever needed. Now to deal with the dictionary part I have understood that I can either create a new dictionary every time I read the file or I can create it once and then just keep updating it (which is the case when I use pointers). Is the latter more computationally efficient?

Below is my attempt to create the dictionary in the same subroutine where I read the file.

```
subroutine ...

use dictionary
type(dict) :: dict_1
type(dict) :: dict_2

        open(file='input_file.dat', file = 30, status='old') ! 

        read(30,*)

        do j=1,no_of_lines
            read(30,*) key_string , value1, value2
            dict_1= dict_1// (key_string .kv. value1)
            dict_2= dict_2// (key_string .kv. value2)
        enddo
```

My doubts are regarding how to: 
(1) create one dictionary instead of two to store the info?
(2) create pointers based on the key strings? (Can I easily convert the key_string from string to a variable to make it a pointer?)
(3) call a value from the key later on in the code?

**Comment by zerothi** [comment]
0) The largest performance hit is probably the IO. Hence the best thing would be to read the files once.
Secondly, I guess that the best performance would be to check whether the `key` exists in `dict_1`, and if not, then add it in both `dict_1` and `dict_2`. However your description does not specify whether you want to overwrite or simply add the new keys.
1) No, two is probably the way to go because they share the same key, otherwise you needed a suffix/prefix which is unique to distinguish between `value1` and `value2`.
2) I don't get what you want to do with string pointers? Could you be more specific?
3) Call a value? Do you mean retrieve the value, if so:
```fortran
call assign(value, dict_1, key)
```

**Comment by hkp888** [comment]
Thank you for your timely response. 

0. Sorry for not being clear. I would like to overwrite the values of existing keys in the dictionary and add new key-value pairs if the key doesn't exist yet. This takes me to the question (2)...
(2) In order to overwrite the value of a key in the dictionary, I should create the dictionary with pointers, right? How do I go about this? I think that I have to create a variable (using type(var)?) with the same name as the key to serve as the pointer (hence convert the key from string to a variable). Or what do you suggest? I have not worked with pointers before.
(1) Got it. That makes sense!
(3) Yes, I meant how to retrieve the value. So I just want to make sure I understand what this is doing: in `call assign (value, dict_1, key)`, we are assigning the key value from dict_1 to a temporary variable called, in this case,  'value' ?

Thank you, Nick!

**Comment by zerothi** [comment]
2) No. Overwriting keys is the same as deallocating the original item, and inserting the new item. The only problem with dictionaries is if you mix `.kv.` and `.kvp.` (or only use the latter) in which case you need to manually figure out whether you _can_ deallocate an item or not. I hope this clarifies.

3) Yes. `value` is then the value in dictionary `dict_1` with key `key`
