### ISSUE TITLE
Creating the dictionary from a read file

### ISSUE THREAD

**Issue by hkp888** [zerothi/fdict#17]
I have an input file that I read before creating a dictionary with its contents. Below is a sample of the input file:

`3` > this is the number of lines following the header.
`"key" "value1" "value2"`
`"2196_202_4" 15582.0 497`
`"2196_8038_4" 15582.0 498`
`"2248_207_4" 15582.0 499`

I was trying to read the file and create a dictionary as follows:

`type(dict) :: dict1`
`type(dict) :: dict2`

`real :: value11`
`integer :: value12`
`character :: key1`
`        open(file='input.dat', unit = 30, status='old')`
`        read(30,*) no_lines`
`        read(30,*)`
`        do j=1,no_lines`
`            read(30,*) key1, value11, value12` 
`            dict1= dict1// (key1.kv.value11)`
`            dict2= dict2// (key1.kv.value12)`
`        enddo`
`        close(30)`
`        call print(dict1)`

However the output I get from the 'print' command is just:
` 2 [s0] (2041543547)`

Not sure what I am doing wrong. Any thoughts?

**Comment by zerothi** [comment]
The `print` routine does not print content, it prints:

```bash
<key> [<type>] (<hash>)
```
since printing a dictionary with a matrix would produce huge amounts of stdout, I decided not to do that.
So everything seems fine, it seems you only have 1 line of data?

**Comment by zerothi** [comment]
note that your `key1` is only 1 character, and thus it can't read more than the first character. This is why your final dictionary only has one element.

**Comment by zerothi** [comment]
@hkp888 I expect the problem to be resolved, if not, please comment and I'll re-open :)

Thanks!

**Comment by hkp888** [comment]
Thanks, Nick! You were very right. 

How do you check if a key exists in a dictionary? 
I am getting some of my retrieved values from the dictionary as zero, so I suspect the key called does not exist for them.

**Comment by zerothi** [comment]
`'key' .in. dict1`
