### ISSUE TITLE
README.md clarification/enhancement

### ISSUE THREAD

**Issue by beatastic** [zerothi/fdict#23]
First off thank you for this project!  It is EXACTLY what I wanted and much better than my homemade attempt.

I have figured out how to use assign/associate from your tests but would have greatly appreciated a small example of each in the README.md for dictionaries the same way you did for variables.  I was confused the .key. and .value. operators instead which only work on dictionaries of one element.

And thank you again.  Learned a lot studying this.

**Comment by zerothi** [comment]
Thank you! I will amend the readme file :)

**Comment by zerothi** [comment]
@beatastic could you please have a look at the updated README? Let me know if there is anything missing! :)

**Comment by beatastic** [comment]
This looks great.  I will have a chance to run the examples this
afternoon.  I had not yet learned about the use of logical success
argument, so that was a good inclusion.

And thank you for the addition of the looping example.  I was doing that
much more awkwardly with wasted lookups.

Thank you so much.  I haven't worked fortran in years and have been doing
languages that have dictionaries instead.  This is a HUGE relief.

**Comment by zerothi** [comment]
Great :)
I'll close then.
